version: '3.9'

services:
  mongodb:
    image: mongo:4.2
    container_name: mg-uri-shortener-db
    environment:
      - MONGO_INITDB_DATABASE=uri-shortener-db
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=123
    ports:
      - "27018:27017"
    volumes:
      - .docker/dev_data:/var/lib/mongo